import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "pt" | "en" | "es" | "de" | "zh";

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: "pt", label: "Português", flag: "🇧🇷" },
  { code: "en", label: "English", flag: "🇺🇸" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "zh", label: "中文", flag: "🇨🇳" },
];

export const LOCALE_MAP: Record<Language, string> = {
  pt: "pt-BR",
  en: "en-US",
  es: "es-ES",
  de: "de-DE",
  zh: "zh-CN",
};

// Dicionário de traduções. Para adicionar mais textos, adicione a chave aqui
// e a tradução correspondente em cada idioma.
const translations: Record<Language, Record<string, string>> = {
  pt: {
    settings: "Configurações",
    history: "Histórico",
    personalization: "Personalização",
    connections: "Conexões",
    appearance: "Aparência",
    language: "Idioma",
    languageDescription: "Escolha o idioma do aplicativo.",
    account: "Conta",
    logout: "Sair da conta",
    login: "Fazer login",
    loginDescription: "Entre para salvar suas conversas e preferências.",
    theme: "Tema",
    themeDescription: "Escolha como a interface deve aparecer.",
    light: "Claro",
    dark: "Escuro",
    system: "Sistema",
    clearHistory: "Limpar histórico",
    newChat: "Nova conversa",
    typeMessage: "Digite sua mensagem...",
    fastMode: "Rápido",
    proMode: "Avançado",
    loading: "Carregando...",
    back: "Voltar",
    primary: "Principal",
    menuActivity: "Atividade",
    menuContext: "Contexto Pessoal",
    menuApps: "Apps Conectados",
    menuTheme: "Tema",
    menuLocation: "Localização",
    activityTitle: "Histórico de Atividades",
    clearAll: "Limpar tudo",
    noActivity: "Nenhuma atividade registrada ainda.",
    contextTitle: "Contexto Pessoal",
    contextDesc: "Adicione informações que a Kojak.AI deve lembrar sobre você para personalizar as respostas.",
    contextPlaceholder: "Ex: Sou desenvolvedor web, prefiro exemplos em TypeScript, trabalho com React...",
    saveContext: "Salvar Contexto",
    saving: "Salvando...",
    savedTitle: "Salvo!",
    savedDesc: "Contexto pessoal atualizado.",
    errorTitle: "Erro",
    errorSaveContext: "Não foi possível salvar o contexto.",
    appsTitle: "Apps Conectados",
    appsDesc: "Gerencie as integrações externas da sua conta.",
    noAppsConnected: "Nenhum app conectado ainda.",
    appsComingSoon: "Em breve você poderá conectar Google Drive, Notion e mais.",
    locationDesc: "Sua localização é usada para personalizar respostas.",
    detecting: "Detectando...",
    locationNotDetected: "Localização não detectada",
    updateLocation: "Atualizar localização",
    defaultUserName: "Usuário",
    clearedTitle: "Histórico limpo",
    clearedDesc: "Todas as atividades foram removidas.",
  },
  en: {
    settings: "Settings",
    history: "History",
    personalization: "Personalization",
    connections: "Connections",
    appearance: "Appearance",
    language: "Language",
    languageDescription: "Choose the app language.",
    account: "Account",
    logout: "Sign out",
    login: "Sign in",
    loginDescription: "Sign in to save your conversations and preferences.",
    theme: "Theme",
    themeDescription: "Choose how the interface should look.",
    light: "Light",
    dark: "Dark",
    system: "System",
    clearHistory: "Clear history",
    newChat: "New chat",
    typeMessage: "Type your message...",
    fastMode: "Fast",
    proMode: "Advanced",
    loading: "Loading...",
    back: "Back",
    primary: "Primary",
    menuActivity: "Activity",
    menuContext: "Personal Context",
    menuApps: "Connected Apps",
    menuTheme: "Theme",
    menuLocation: "Location",
    activityTitle: "Activity History",
    clearAll: "Clear all",
    noActivity: "No activity recorded yet.",
    contextTitle: "Personal Context",
    contextDesc: "Add information Kojak.AI should remember about you to personalize responses.",
    contextPlaceholder: "E.g: I'm a web developer, I prefer TypeScript examples, I work with React...",
    saveContext: "Save Context",
    saving: "Saving...",
    savedTitle: "Saved!",
    savedDesc: "Personal context updated.",
    errorTitle: "Error",
    errorSaveContext: "Could not save the context.",
    appsTitle: "Connected Apps",
    appsDesc: "Manage your account's external integrations.",
    noAppsConnected: "No apps connected yet.",
    appsComingSoon: "Soon you'll be able to connect Google Drive, Notion and more.",
    locationDesc: "Your location is used to personalize responses.",
    detecting: "Detecting...",
    locationNotDetected: "Location not detected",
    updateLocation: "Update location",
    defaultUserName: "User",
    clearedTitle: "History cleared",
    clearedDesc: "All activities were removed.",
  },
  es: {
    settings: "Configuración",
    history: "Historial",
    personalization: "Personalización",
    connections: "Conexiones",
    appearance: "Apariencia",
    language: "Idioma",
    languageDescription: "Elige el idioma de la aplicación.",
    account: "Cuenta",
    logout: "Cerrar sesión",
    login: "Iniciar sesión",
    loginDescription: "Inicia sesión para guardar tus conversaciones y preferencias.",
    theme: "Tema",
    themeDescription: "Elige cómo debe verse la interfaz.",
    light: "Claro",
    dark: "Oscuro",
    system: "Sistema",
    clearHistory: "Borrar historial",
    newChat: "Nueva conversación",
    typeMessage: "Escribe tu mensaje...",
    fastMode: "Rápido",
    proMode: "Avanzado",
    loading: "Cargando...",
    back: "Volver",
    primary: "Principal",
    menuActivity: "Actividad",
    menuContext: "Contexto Personal",
    menuApps: "Apps Conectadas",
    menuTheme: "Tema",
    menuLocation: "Ubicación",
    activityTitle: "Historial de Actividad",
    clearAll: "Borrar todo",
    noActivity: "Ninguna actividad registrada todavía.",
    contextTitle: "Contexto Personal",
    contextDesc: "Añade información que Kojak.AI debe recordar sobre ti para personalizar las respuestas.",
    contextPlaceholder: "Ej: Soy desarrollador web, prefiero ejemplos en TypeScript, trabajo con React...",
    saveContext: "Guardar Contexto",
    saving: "Guardando...",
    savedTitle: "¡Guardado!",
    savedDesc: "Contexto personal actualizado.",
    errorTitle: "Error",
    errorSaveContext: "No se pudo guardar el contexto.",
    appsTitle: "Apps Conectadas",
    appsDesc: "Gestiona las integraciones externas de tu cuenta.",
    noAppsConnected: "Ninguna app conectada todavía.",
    appsComingSoon: "Pronto podrás conectar Google Drive, Notion y más.",
    locationDesc: "Tu ubicación se usa para personalizar las respuestas.",
    detecting: "Detectando...",
    locationNotDetected: "Ubicación no detectada",
    updateLocation: "Actualizar ubicación",
    defaultUserName: "Usuario",
    clearedTitle: "Historial borrado",
    clearedDesc: "Todas las actividades fueron eliminadas.",
  },
  de: {
    settings: "Einstellungen",
    history: "Verlauf",
    personalization: "Personalisierung",
    connections: "Verbindungen",
    appearance: "Erscheinungsbild",
    language: "Sprache",
    languageDescription: "Wähle die Sprache der App.",
    account: "Konto",
    logout: "Abmelden",
    login: "Anmelden",
    loginDescription: "Melde dich an, um deine Unterhaltungen und Einstellungen zu speichern.",
    theme: "Design",
    themeDescription: "Wähle, wie die Oberfläche aussehen soll.",
    light: "Hell",
    dark: "Dunkel",
    system: "System",
    clearHistory: "Verlauf löschen",
    newChat: "Neue Unterhaltung",
    typeMessage: "Nachricht eingeben...",
    fastMode: "Schnell",
    proMode: "Erweitert",
    loading: "Wird geladen...",
    back: "Zurück",
    primary: "Hauptsprache",
    menuActivity: "Aktivität",
    menuContext: "Persönlicher Kontext",
    menuApps: "Verbundene Apps",
    menuTheme: "Design",
    menuLocation: "Standort",
    activityTitle: "Aktivitätsverlauf",
    clearAll: "Alles löschen",
    noActivity: "Noch keine Aktivität aufgezeichnet.",
    contextTitle: "Persönlicher Kontext",
    contextDesc: "Füge Informationen hinzu, die sich Kojak.AI merken soll, um Antworten zu personalisieren.",
    contextPlaceholder: "Z.B: Ich bin Webentwickler, bevorzuge TypeScript-Beispiele, arbeite mit React...",
    saveContext: "Kontext speichern",
    saving: "Wird gespeichert...",
    savedTitle: "Gespeichert!",
    savedDesc: "Persönlicher Kontext aktualisiert.",
    errorTitle: "Fehler",
    errorSaveContext: "Der Kontext konnte nicht gespeichert werden.",
    appsTitle: "Verbundene Apps",
    appsDesc: "Verwalte die externen Integrationen deines Kontos.",
    noAppsConnected: "Noch keine App verbunden.",
    appsComingSoon: "Bald kannst du Google Drive, Notion und mehr verbinden.",
    locationDesc: "Dein Standort wird zur Personalisierung der Antworten verwendet.",
    detecting: "Wird erkannt...",
    locationNotDetected: "Standort nicht erkannt",
    updateLocation: "Standort aktualisieren",
    defaultUserName: "Benutzer",
    clearedTitle: "Verlauf gelöscht",
    clearedDesc: "Alle Aktivitäten wurden entfernt.",
  },
  zh: {
    settings: "设置",
    history: "历史记录",
    personalization: "个性化",
    connections: "连接",
    appearance: "外观",
    language: "语言",
    languageDescription: "选择应用语言。",
    account: "账户",
    logout: "退出登录",
    login: "登录",
    loginDescription: "登录以保存您的对话和偏好设置。",
    theme: "主题",
    themeDescription: "选择界面的外观。",
    light: "浅色",
    dark: "深色",
    system: "系统",
    clearHistory: "清除历史记录",
    newChat: "新对话",
    typeMessage: "输入消息...",
    fastMode: "快速",
    proMode: "高级",
    loading: "加载中...",
    back: "返回",
    primary: "主要语言",
    menuActivity: "活动",
    menuContext: "个人背景",
    menuApps: "已连接的应用",
    menuTheme: "主题",
    menuLocation: "位置",
    activityTitle: "活动历史",
    clearAll: "全部清除",
    noActivity: "暂无活动记录。",
    contextTitle: "个人背景",
    contextDesc: "添加 Kojak.AI 应记住的信息，以个性化回答。",
    contextPlaceholder: "例如：我是网页开发者，偏好 TypeScript 示例，使用 React 工作...",
    saveContext: "保存背景信息",
    saving: "保存中...",
    savedTitle: "已保存！",
    savedDesc: "个人背景已更新。",
    errorTitle: "错误",
    errorSaveContext: "无法保存背景信息。",
    appsTitle: "已连接的应用",
    appsDesc: "管理您账户的外部集成。",
    noAppsConnected: "尚未连接任何应用。",
    appsComingSoon: "即将支持连接 Google Drive、Notion 等。",
    locationDesc: "您的位置用于个性化回答。",
    detecting: "检测中...",
    locationNotDetected: "未检测到位置",
    updateLocation: "更新位置",
    defaultUserName: "用户",
    clearedTitle: "历史已清除",
    clearedDesc: "所有活动已被移除。",
  },
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

const STORAGE_KEY = "kojak-language";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(STORAGE_KEY) as Language | null;
    return saved && translations[saved] ? saved : "pt";
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => setLanguageState(lang);

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations.pt[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage precisa estar dentro de um LanguageProvider");
  return ctx;
}