import { Download, Copy, Check, User, Sparkles, Volume2, ImagePlus } from "lucide-react";
import { useState } from "react";
import { cn } from "@/lib/utils";
import ReactMarkdown from "react-markdown";

export interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  type?: "text" | "code" | "image" | "video";
  language?: string;
  media_url?: string;
  created_at?: string;
}

interface ChatMessageProps {
  message: Message;
  onSpeak?: (text: string) => void;
  onSelectReference?: (url: string) => void;
}

export function ChatMessage({ message, onSpeak, onSelectReference }: ChatMessageProps) {
  const [copied, setCopied] = useState(false);
  const isUser = message.role === "user";

  const handleCopy = async (text: string) => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = async (url: string, filename: string) => {
    try {
      const response = await fetch(url);
      const blob = await response.blob();
      const downloadUrl = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = downloadUrl;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(downloadUrl);
    } catch (error) {
      console.error("Download failed:", error);
    }
  };

  const formatTime = () => {
    if (message.created_at) {
      return new Date(message.created_at).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" });
    }
    return new Date().toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" });
  };

  return (
    <div className={cn("flex gap-3 animate-fade-in", isUser ? "flex-row-reverse" : "flex-row")}>
      <div className={cn("flex-shrink-0 w-9 h-9 rounded-xl flex items-center justify-center", isUser ? "bg-gradient-purple glow-purple" : "bg-gradient-to-br from-primary/40 to-secondary/30 border border-primary/30")}>
        {isUser ? <User className="w-5 h-5 text-white" /> : <Sparkles className="w-5 h-5 text-primary" />}
      </div>

      <div className={cn("max-w-[85%] md:max-w-[75%] rounded-2xl px-4 py-3", isUser ? "bubble-user text-white rounded-tr-sm" : "bubble-ai rounded-tl-sm")}>
        
        {/* User image attachment */}
        {isUser && message.media_url && (
          <div className="mb-2 rounded-xl overflow-hidden">
            <img src={message.media_url} alt="Imagem anexada" className="w-full max-w-xs rounded-xl" />
          </div>
        )}

        {(!message.type || message.type === "text" || message.type === "code") && (
          <div className={cn("text-sm leading-relaxed prose prose-sm max-w-none", isUser ? "prose-invert" : "prose-kojak")}>
            <ReactMarkdown>{message.content}</ReactMarkdown>
          </div>
        )}

        {message.type === "image" && message.media_url && (
          <div className="relative group rounded-xl overflow-hidden mt-2">
            <img src={message.media_url} alt="Generated by Kojak Vision" className="w-full max-w-md rounded-xl" />
            <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-4">
              <button onClick={() => handleDownload(message.media_url!, "kojak-image.png")} className="p-3 bg-white/20 text-white rounded-full hover:scale-110 transition-transform backdrop-blur-sm">
                <Download className="w-5 h-5" />
              </button>
              {!isUser && onSelectReference && (
                <button 
                  onClick={() => onSelectReference(message.media_url!)} 
                  className="p-3 bg-gradient-purple text-white rounded-full hover:scale-110 transition-transform glow-purple"
                  title="Usar como Alvo (Troca de Rosto)"
                >
                  <ImagePlus className="w-5 h-5" />
                </button>
              )}
            </div>
          </div>
        )}

        {message.type === "video" && message.media_url && (
          <div className="mt-2 rounded-xl overflow-hidden">
            <video src={message.media_url} controls className="w-full max-w-md rounded-xl" />
          </div>
        )}

        {/* Action buttons for assistant messages */}
        {!isUser && (
          <div className="flex items-center gap-2 mt-2 pt-2 border-t border-white/10">
            <button
              onClick={() => handleCopy(message.content)}
              className="flex items-center gap-1 px-2 py-1 rounded-lg text-xs text-muted-foreground hover:text-foreground hover:bg-white/5 transition-all"
              title="Copiar resposta"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? "Copiado" : "Copiar"}</span>
            </button>
            {onSpeak && (
              <button
                onClick={() => onSpeak(message.content)}
                className="flex items-center gap-1 px-2 py-1 rounded-lg text-xs text-muted-foreground hover:text-foreground hover:bg-white/5 transition-all"
                title="Ouvir resposta"
              >
                <Volume2 className="w-3.5 h-3.5" />
                <span>Ouvir</span>
              </button>
            )}
          </div>
        )}

        <div className={cn("mt-2 text-[10px] font-medium opacity-50", isUser ? "text-right" : "text-left")}>
          {formatTime()}
        </div>
      </div>
    </div>
  );
}
